// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelRow = { reminder_id: number, channel: string, status: string, attempts: number, last_error: string | null, last_attempt_at: string | null, };
