// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Agent = { name: string, entry_count: number, 
/**
 * Most recent date that has an entry, in `YYYY-MM-DD` (sorted
 * lexicographically — diary filenames already match that
 * format, no parse).
 */
last_entry_date: string | null, };
