// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatRow = { id: string, title: string | null, claude_session_id: string | null, created_at: string, last_active: string, };
