// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatRow } from "./ChatRow";
import type { MessageRow } from "./MessageRow";

export type ChatDetail = { chat: ChatRow, messages: Array<MessageRow>, };
