// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DockerContainer = { id: string, names: Array<string>, image: string, state: string, status: string, };
