// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatGlance } from "./ChatGlance";
import type { DiaryGlance } from "./DiaryGlance";
import type { NewsGlance } from "./NewsGlance";
import type { NextFireGlance } from "./NextFireGlance";
import type { VaultGlance } from "./VaultGlance";

export type Glances = { next_fire: NextFireGlance | null, latest_vault: VaultGlance | null, latest_diary: DiaryGlance | null, top_news: NewsGlance | null, latest_chat: ChatGlance | null, };
