// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an agent is launched — determines how liveness is probed.
 */
export type Launch = "launchd-daemon" | "launchd-cron" | "in-process" | "on-demand";
