// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NextFireGlance = { id: number, title_or_body: string, next_fire_at: string, channels: string | null, };
