// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelRow } from "./ChannelRow";

export type ReminderView = { channels: Array<ChannelRow>, id: number, 
/**
 * ADR-015: short human-friendly name. When None, display layers
 * fall back to `body` (if non-empty) or a derived label from
 * `system_prompt`. Skill-fire reminders should always set this.
 */
title: string | null, body: string, cron: string, one_shot: boolean, status: string, next_fire_at: string | null, last_fired_at: string | null, paused_until: string | null, created_at: string, created_by: string, 
/**
 * ADR-008: when Some, this reminder fires by spawning a one-shot
 * Claude session and using the stored string as the first ask()
 * payload (the firing path adds its own generic persona via
 * --append-system-prompt). XOR with `body`: exactly one is
 * non-empty, enforced at CLI insert time.
 */
system_prompt: string | null, };
