// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunDto = { run_id: string, started_at: string, finished_at: string | null, items_new: number, items_notable: number, ok: number, };
