// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceDto = { id: number, name: string, url: string, enabled: number, last_fetched_at: string | null, last_error: string | null, };
