//! preference-learner — reads news votes, asks Claude to derive preferences,
//! writes `news_preferences.md` into Tier 2 shared memory.
//!
//! The fetcher reads news_preferences.md and uses it to score notability.
//! Run weekly via launchd.

use anyhow::{Context, Result};
use chrono::Utc;
use nucleus_core::{
    claude::PermissionMode,
    claude_session::{AskOptions, Session, SpawnOptions},
    db, diary, memory,
};
use sqlx::SqlitePool;

const AGENT_NAME: &str = "preference-learner";
const NEWS_DB: &str = "memory/news.db";
const MEMORY_NAME: &str = "news_preferences";

#[derive(sqlx::FromRow, serde::Serialize, Debug)]
struct VotedItem {
    item_id: String,
    title: String,
    summary: Option<String>,
    notable_score: Option<f64>,
    notable_reason: Option<String>,
    upvotes: i64,
    downvotes: i64,
}

#[tokio::main]
async fn main() -> Result<()> {
    nucleus_core::init_tracing();
    let settings = nucleus_core::config::Settings::load().context("loading settings")?;
    let workspace_root = std::env::current_dir()?;
    let pool = db::open(&workspace_root.join(NEWS_DB)).await
        .context("opening news.db")?;

    let voted = collect_votes(&pool).await?;
    if voted.is_empty() {
        tracing::info!("preference-learner: no votes yet, nothing to learn");
        let _ = diary::record_observation(&workspace_root, AGENT_NAME, "run", "no votes", diary::Tag::Observation);
        return Ok(());
    }
    tracing::info!("preference-learner: analyzing {} voted items", voted.len());

    let _ = tokio::process::Command::new("tmux")
        .args(["kill-session", "-t", "nucleus-preference-learner"])
        .output()
        .await;

    let prompt = build_prompt(&voted, &settings.identity.user_name)?;
    let mut session = Session::spawn(SpawnOptions {
        workspace_root: workspace_root.clone(),
        permission_mode: Some(PermissionMode::Auto),
        tmux_session: "nucleus-preference-learner".into(),
        window_name: Some("derive".into()),
        ..SpawnOptions::default()
    })
    .await
    .context("spawning claude session")?;
    let body = session.ask(&prompt, AskOptions::default()).await?;
    let _ = session.close().await;
    let body = body.trim().to_string();
    let mem = memory::Memory {
        name: MEMORY_NAME.into(),
        description: "Learned news preferences from upvotes/downvotes — used by news-fetcher".into(),
        kind: memory::Kind::Reference,
        body: format!(
            "_Auto-generated by preference-learner at {}._\n\n{}",
            Utc::now().to_rfc3339(),
            body
        ),
    };
    let path = memory::promote(&mem)?;
    tracing::info!("preference-learner: wrote {:?}", path);

    let _ = diary::record_observation(
        &workspace_root,
        AGENT_NAME,
        "run",
        &format!("derived preferences from {} voted items → {:?}", voted.len(), path),
        diary::Tag::Observation,
    );
    Ok(())
}

async fn collect_votes(pool: &SqlitePool) -> Result<Vec<VotedItem>> {
    let rows: Vec<VotedItem> = sqlx::query_as::<_, VotedItem>(r#"
        SELECT i.id AS item_id, i.title, i.summary, i.notable_score, i.notable_reason,
               COALESCE((SELECT COUNT(*) FROM votes v WHERE v.item_id = i.id AND v.vote =  1), 0) AS upvotes,
               COALESCE((SELECT COUNT(*) FROM votes v WHERE v.item_id = i.id AND v.vote = -1), 0) AS downvotes
        FROM items i
        WHERE EXISTS (SELECT 1 FROM votes v WHERE v.item_id = i.id)
        ORDER BY (upvotes - downvotes) DESC
    "#).fetch_all(pool).await?;
    Ok(rows)
}

fn build_prompt(voted: &[VotedItem], user_name: &str) -> Result<String> {
    let json = serde_json::to_string_pretty(voted)?;
    Ok(format!(r#"You are deriving {user_name}'s news preferences from their upvote/downvote history.

Here are items they have voted on (positive = upvote count, negative = downvote count):
{json}

Write a concise markdown brief describing:
1. **Topics they favor** — what kinds of stories they upvote
2. **Topics they reject** — what kinds of stories they downvote
3. **Style preferences** — depth (deep dives vs news bites), source preferences, etc.

Format as markdown sections. Be specific (cite signals from the data). Lead with a one-sentence
summary at the top. Do NOT preamble or wrap in fences — output the markdown body directly.

This will be loaded by the news-fetcher to bias notability scoring on the next run."#))
}
